/* boot.c - SacabambaspOS UEFI boot stage.
 *
 * Foundation of SacabambaspOS. Runs as an EFI application (BOOTX64.EFI /
 * BOOTIA32.EFI) off the USB's EFI System Partition. It:
 *   1. finds the Graphics Output Protocol (the panel framebuffer),
 *   2. loads the raw BGRA image blob (SACABASP.RAW) from the same volume,
 *   3. scales it to fit and blits it centred on a solid background,
 *   4. idles forever (live/try-it mode).
 *
 * It NEVER writes to any disk. Nothing is installed. Pull the USB and the
 * machine is untouched.
 */
#include "efi.h"
#include "version.h"
#include "font8x16.h"                 /* generated by tools/mkfont.py */
#include "../shared/bootinfo.h"

static EFI_SYSTEM_TABLE *ST;
static EFI_BOOT_SERVICES *BS;

/* freestanding helpers (gcc may emit calls to these) */
void *memset(void *d, int c, unsigned long n){unsigned char*p=d;while(n--)*p++=(unsigned char)c;return d;}
void *memcpy(void *d, const void *s, unsigned long n){unsigned char*a=d;const unsigned char*b=s;while(n--)*a++=*b++;return d;}

#if !defined(__x86_64__)
/* ia32 has no native 64-bit divide; gcc emits calls to these libgcc
 * intrinsics, and we link no libgcc. -Bsymbolic binds the calls directly at
 * link time: no PLT, no runtime relocations, empty-.reloc trick intact. */
static UINT64 udivmod64(UINT64 n, UINT64 d, UINT64 *rem){
  UINT64 q=0, r=0;
  for(int i=63;i>=0;i--){
    r=(r<<1)|((n>>i)&1);
    if(r>=d){ r-=d; q|=1ULL<<i; }
  }
  if(rem)*rem=r;
  return q;
}
UINT64 __udivdi3(UINT64 n, UINT64 d){ return udivmod64(n,d,NULL); }
UINT64 __umoddi3(UINT64 n, UINT64 d){ UINT64 r; udivmod64(n,d,&r); return r; }
#endif

/* ---- boot log ----------------------------------------------------------- */
/* EFI text attributes: fg | bg<<4 */
#define ATTR_DIM    0x08  /* dark grey  */
#define ATTR_TEXT   0x07  /* light grey */
#define ATTR_BRIGHT 0x0F  /* white      */
#define ATTR_OK     0x0A  /* green      */
#define ATTR_FAIL   0x0C  /* red        */
#define ATTR_TITLE  0x0B  /* cyan       */
#define ATTR_WARN   0x0E  /* yellow     */

/* Every log character is also recorded here (with its color) so the boot
 * console overlay on the splash can replay the whole log and keep appending
 * to it. Once the overlay is live (ol_live) ConOut is never touched again -
 * the firmware text console would paint over the framebuffer. */
#define OL_COLS 128
#define OL_ROWS 160
typedef struct { char ch; UINT8 attr; } OlCell;
static OlCell ol_log[OL_ROWS][OL_COLS];
static UINT32 ol_row, ol_col;
static UINTN  cur_attr = ATTR_TEXT;
static int    ol_live;
static void   ol_flush(void);

static void rec_putc(char c){
  if(c=='\r') return;
  if(c!='\n' && ol_col<OL_COLS){
    ol_log[ol_row][ol_col]=(OlCell){c,(UINT8)(cur_attr&0x0F)};
    ol_col++; return;
  }
  /* newline (or forced wrap) */
  if(ol_row==OL_ROWS-1){
    for(UINT32 r=0;r<OL_ROWS-1;r++) memcpy(ol_log[r],ol_log[r+1],sizeof(ol_log[0]));
    memset(ol_log[OL_ROWS-1],0,sizeof(ol_log[0]));
  } else ol_row++;
  ol_col=0;
  if(c!='\n') rec_putc(c);
}

static void puts16(CHAR16 *s){
  if(ST&&ST->ConOut&&!ol_live) ST->ConOut->OutputString(ST->ConOut, s);
  int nl=0;
  for(CHAR16 *p=s;*p;p++){ rec_putc(*p<128?(char)*p:'?'); if(*p==u'\n') nl=1; }
  if(nl&&ol_live) ol_flush();
}

static void con_attr(UINTN a){
  cur_attr=a;
  if(!ol_live && ST->ConOut && ST->ConOut->SetAttribute)
    ST->ConOut->SetAttribute(ST->ConOut,a);
}

static void log_tag(CHAR16 *tag, UINTN color){
  con_attr(ATTR_DIM);  puts16(u"  [");
  con_attr(color);     puts16(tag);
  con_attr(ATTR_DIM);  puts16(u"] ");
  con_attr(ATTR_TEXT);
}
static void log_ok(CHAR16 *m)  { log_tag(u"  OK  ",ATTR_OK);   puts16(m); puts16(u"\r\n"); }
static void log_fail(CHAR16 *m){ log_tag(u" FAIL ",ATTR_FAIL); puts16(m); puts16(u"\r\n"); }

static void print_u(UINT64 v){
  CHAR16 b[21]; UINTN i=20; b[20]=0;
  if(!v) b[--i]=u'0';
  while(v){ b[--i]=(CHAR16)(u'0'+v%10); v/=10; }
  puts16(b+i);
}
static void print_hex(UINT64 v){
  CHAR16 b[19]; UINTN i=18; b[18]=0;
  if(!v) b[--i]=u'0';
  while(v){ UINT64 d=v&0xF; b[--i]=(CHAR16)(d<10?u'0'+d:u'A'+d-10); v>>=4; }
  puts16(u"0x"); puts16(b+i);
}

/* SBMP asset header, must match tools/mkasset.py */
typedef struct {
  UINT8  magic[4];  /* "SBMP" */
  UINT32 version, width, height, bpp, pixfmt, r0, r1;
} SbmpHeader;

/* Build a native framebuffer pixel from 8-bit RGB per the mode's format. */
static UINT32 mkpix(EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *mi, UINT8 r, UINT8 g, UINT8 b){
  switch(mi->PixelFormat){
    case PixelBlueGreenRedReserved8BitPerColor: return ((UINT32)r<<16)|((UINT32)g<<8)|b;
    case PixelRedGreenBlueReserved8BitPerColor: return ((UINT32)b<<16)|((UINT32)g<<8)|r;
    case PixelBitMask: {
      EFI_PIXEL_BITMASK *m=&mi->PixelInformation; UINT32 v=0;
      /* find each mask's shift and width */
      UINT32 rm=m->RedMask, gm=m->GreenMask, bm=m->BlueMask;
      int rs=0,gs=0,bs=0; while(rm&&!(rm&1)){rm>>=1;rs++;} while(gm&&!(gm&1)){gm>>=1;gs++;} while(bm&&!(bm&1)){bm>>=1;bs++;}
      int rw=0,gw=0,bw=0; while(rm&1){rm>>=1;rw++;} while(gm&1){gm>>=1;gw++;} while(bm&1){bm>>=1;bw++;}
      /* scale each 8-bit channel into the mask's width: keep the TOP bits for
       * narrow masks (5:6:5 etc), shift up for wide ones */
      v |= ((rw<8 ? (UINT32)r>>(8-rw) : (UINT32)r<<(rw-8))<<rs) & m->RedMask;
      v |= ((gw<8 ? (UINT32)g>>(8-gw) : (UINT32)g<<(gw-8))<<gs) & m->GreenMask;
      v |= ((bw<8 ? (UINT32)b>>(8-bw) : (UINT32)b<<(bw-8))<<bs) & m->BlueMask;
      return v;
    }
    default: return ((UINT32)r<<16)|((UINT32)g<<8)|b;
  }
}

static EFI_STATUS load_asset(EFI_HANDLE image, UINT8 **out, UINTN *outsz){
  EFI_GUID li_guid = EFI_LOADED_IMAGE_PROTOCOL_GUID;
  EFI_GUID fs_guid = EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_GUID;
  EFI_LOADED_IMAGE_PROTOCOL *li=NULL;
  EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *fs=NULL;
  EFI_FILE_PROTOCOL *root=NULL, *f=NULL;
  EFI_STATUS s;

  s = BS->HandleProtocol(image, &li_guid, (VOID**)&li);
  if(s) return s;
  s = BS->HandleProtocol(li->DeviceHandle, &fs_guid, (VOID**)&fs);
  if(s) return s;
  s = fs->OpenVolume(fs, &root);
  if(s) return s;

  CHAR16 *names[] = { u"\\SACABASP.RAW", u"SACABASP.RAW", u"\\EFI\\BOOT\\SACABASP.RAW" };
  for(int i=0;i<3 && !f;i++){
    if(root->Open(root, &f, names[i], EFI_FILE_MODE_READ, 0)) f=NULL;
  }
  if(!f) return EFI_NOT_FOUND;

  /* read header */
  SbmpHeader h; UINTN n=sizeof(h);
  s=f->Read(f,&n,&h); if(s||n!=sizeof(h)){ f->Close(f); return s?s:EFI_LOAD_ERROR; }
  if(!(h.magic[0]=='S'&&h.magic[1]=='B'&&h.magic[2]=='M'&&h.magic[3]=='P')){ f->Close(f); return EFI_LOAD_ERROR; }
  /* sanity: reject unknown format revisions and absurd dims before the
   * multiply (also guards 32-bit UINTN) */
  if(h.version!=1||h.pixfmt!=0||h.bpp!=32){ f->Close(f); return EFI_UNSUPPORTED; }
  if(h.width==0||h.height==0||h.width>8192||h.height>8192){ f->Close(f); return EFI_LOAD_ERROR; }

  UINTN pixbytes = (UINTN)h.width*h.height*4;
  UINT8 *buf=NULL;
  s=BS->AllocatePool(EfiLoaderData, sizeof(h)+pixbytes, (VOID**)&buf); if(s){ f->Close(f); return s; }
  memcpy(buf,&h,sizeof(h));
  /* Read the payload in <=1MiB chunks and tolerate short reads: some real
   * firmware FAT drivers misbehave on multi-MB single reads (same workaround
   * the Linux EFI stub uses). File position is already past the header. */
  UINTN got=0;
  while(got<pixbytes){
    UINTN want=pixbytes-got;
    if(want>1024*1024) want=1024*1024;
    s=f->Read(f,&want,buf+sizeof(h)+got);
    if(s||want==0) break;
    got+=want;
  }
  f->Close(f);
  if(s){ BS->FreePool(buf); return s; }
  if(got!=pixbytes){ BS->FreePool(buf); return EFI_LOAD_ERROR; }  /* truncated */
  *out=buf; *outsz=sizeof(h)+got; return EFI_SUCCESS;
}

/* Read a whole file from the boot volume into a fresh pool buffer (up to
 * cap bytes), trying each candidate path. Chunked reads: same firmware FAT
 * workaround as load_asset. */
static EFI_STATUS load_file(EFI_HANDLE image, CHAR16 **names, int nnames,
                            UINTN cap, UINT8 **out, UINTN *outsz){
  EFI_GUID li_guid = EFI_LOADED_IMAGE_PROTOCOL_GUID;
  EFI_GUID fs_guid = EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_GUID;
  EFI_LOADED_IMAGE_PROTOCOL *li=NULL;
  EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *fs=NULL;
  EFI_FILE_PROTOCOL *root=NULL, *f=NULL;
  EFI_STATUS s;

  s = BS->HandleProtocol(image, &li_guid, (VOID**)&li);           if(s) return s;
  s = BS->HandleProtocol(li->DeviceHandle, &fs_guid, (VOID**)&fs); if(s) return s;
  s = fs->OpenVolume(fs, &root);                                   if(s) return s;
  for(int i=0;i<nnames && !f;i++)
    if(root->Open(root, &f, names[i], EFI_FILE_MODE_READ, 0)) f=NULL;
  if(!f) return EFI_NOT_FOUND;

  UINT8 *buf=NULL;
  s=BS->AllocatePool(EfiLoaderData, cap, (VOID**)&buf);
  if(s){ f->Close(f); return s; }
  UINTN got=0;
  while(got<cap){
    UINTN want=cap-got;
    if(want>1024*1024) want=1024*1024;
    s=f->Read(f,&want,buf+got);
    if(s||want==0) break;
    got+=want;
  }
  f->Close(f);
  if(s){ BS->FreePool(buf); return s; }
  if(got==0){ BS->FreePool(buf); return EFI_LOAD_ERROR; }
  if(got==cap){ BS->FreePool(buf); return EFI_LOAD_ERROR; }   /* larger than cap */
  *out=buf; *outsz=got; return EFI_SUCCESS;
}

#if defined(__x86_64__)
/* ---- kernel: ELF64 static-PIE loader ------------------------------------ */
typedef struct {
  UINT8 e_ident[16]; UINT16 e_type,e_machine; UINT32 e_version;
  UINT64 e_entry,e_phoff,e_shoff; UINT32 e_flags;
  UINT16 e_ehsize,e_phentsize,e_phnum,e_shentsize,e_shnum,e_shstrndx;
} Elf64_Ehdr;
typedef struct {
  UINT32 p_type,p_flags;
  UINT64 p_offset,p_vaddr,p_paddr,p_filesz,p_memsz,p_align;
} Elf64_Phdr;
typedef struct { INT64 d_tag; UINT64 d_val; } Elf64_Dyn;
typedef struct { UINT64 r_offset,r_info; INT64 r_addend; } Elf64_Rela;
#define PT_LOAD    1
#define PT_DYNAMIC 2
#define DT_NULL    0
#define DT_RELA    7
#define DT_RELASZ  8
#define R_X86_64_RELATIVE 8

/* Load KERNEL.ELF anywhere in RAM (EfiLoaderCode so post-EBS NX policies
 * keep it executable) and apply its R_X86_64_RELATIVE relocations. */
static EFI_STATUS kernel_load(EFI_HANDLE image, UINT64 *entry_out, UINT64 *base_out){
  CHAR16 *names[]={u"\\KERNEL.ELF", u"KERNEL.ELF", u"\\EFI\\BOOT\\KERNEL.ELF"};
  UINT8 *file=NULL; UINTN fsz=0;
  EFI_STATUS s=load_file(image,names,3,8*1024*1024,&file,&fsz);
  if(s) return s;

  Elf64_Ehdr *eh=(Elf64_Ehdr*)file;
  if(fsz<sizeof(*eh) || eh->e_ident[0]!=0x7F||eh->e_ident[1]!='E'||
     eh->e_ident[2]!='L'||eh->e_ident[3]!='F'||
     eh->e_ident[4]!=2 /*64-bit*/ || eh->e_ident[5]!=1 /*LE*/ ||
     eh->e_machine!=62 /*x86-64*/ || eh->e_type!=3 /*ET_DYN*/){
    BS->FreePool(file); return EFI_LOAD_ERROR;
  }

  Elf64_Phdr *ph=(Elf64_Phdr*)(file+eh->e_phoff);
  UINT64 lo=~0ULL, hi=0;
  for(int i=0;i<eh->e_phnum;i++){
    if(ph[i].p_type!=PT_LOAD) continue;
    if(ph[i].p_vaddr<lo) lo=ph[i].p_vaddr;
    if(ph[i].p_vaddr+ph[i].p_memsz>hi) hi=ph[i].p_vaddr+ph[i].p_memsz;
  }
  if(hi<=lo){ BS->FreePool(file); return EFI_LOAD_ERROR; }
  lo &= ~0xFFFULL;

  UINTN pages=(UINTN)((hi-lo+0xFFF)>>12);
  UINT64 base=0;
  s=BS->AllocatePages(AllocateAnyPages,EfiLoaderCode,pages,&base);
  if(s){ BS->FreePool(file); return s; }
  UINT64 slide=base-lo;
  memset((void*)(UINTN)base,0,pages<<12);

  for(int i=0;i<eh->e_phnum;i++){
    if(ph[i].p_type!=PT_LOAD) continue;
    if(ph[i].p_offset+ph[i].p_filesz>fsz){ BS->FreePool(file); return EFI_LOAD_ERROR; }
    memcpy((void*)(UINTN)(slide+ph[i].p_vaddr), file+ph[i].p_offset, ph[i].p_filesz);
  }

  /* relocations from PT_DYNAMIC (static PIE: R_X86_64_RELATIVE only) */
  for(int i=0;i<eh->e_phnum;i++){
    if(ph[i].p_type!=PT_DYNAMIC) continue;
    Elf64_Dyn *dyn=(Elf64_Dyn*)(UINTN)(slide+ph[i].p_vaddr);
    UINT64 rela=0, relasz=0;
    for(Elf64_Dyn *d=dyn; d->d_tag!=DT_NULL; d++){
      if(d->d_tag==DT_RELA)   rela=slide+d->d_val;
      if(d->d_tag==DT_RELASZ) relasz=d->d_val;
    }
    for(UINT64 off=0; off+sizeof(Elf64_Rela)<=relasz; off+=sizeof(Elf64_Rela)){
      Elf64_Rela *r=(Elf64_Rela*)(UINTN)(rela+off);
      if((r->r_info&0xFFFFFFFF)!=R_X86_64_RELATIVE){ BS->FreePool(file); return EFI_UNSUPPORTED; }
      *(UINT64*)(UINTN)(slide+r->r_offset)=slide+r->r_addend;
    }
  }

  UINT64 entry=slide+eh->e_entry;   /* read before the file buffer dies */
  BS->FreePool(file);
  *entry_out=entry;
  *base_out=base;
  return EFI_SUCCESS;
}

/* ---- boot info + ExitBootServices --------------------------------------- */
static SbosBootInfo bootinfo;

static int guid_eq(EFI_GUID *a, EFI_GUID *b){
  UINT8 *x=(UINT8*)a,*y=(UINT8*)b;
  for(int i=0;i<16;i++) if(x[i]!=y[i]) return 0;
  return 1;
}

static UINT64 find_rsdp(void){
  EFI_GUID acpi2=EFI_ACPI_20_TABLE_GUID, acpi1=EFI_ACPI_10_TABLE_GUID;
  UINT64 v1=0;
  for(UINTN i=0;i<ST->NumberOfTableEntries;i++){
    EFI_CONFIGURATION_TABLE *t=&ST->ConfigurationTable[i];
    if(guid_eq(&t->VendorGuid,&acpi2)) return (UINT64)(UINTN)t->VendorTable;
    if(guid_eq(&t->VendorGuid,&acpi1)) v1=(UINT64)(UINTN)t->VendorTable;
  }
  return v1;
}

/* GetMemoryMap + ExitBootServices, retried: any allocation between the two
 * changes the map key, and the first EBS attempt itself may alter the map. */
static EFI_STATUS exit_boot_services(EFI_HANDLE image, UINT64 *total_ram){
  EFI_MEMORY_DESCRIPTOR *map=NULL;
  UINTN msz=0,key=0,dsz=0; UINT32 dver=0;
  for(int tries=0;tries<4;tries++){
    msz=0;
    BS->GetMemoryMap(&msz,NULL,&key,&dsz,&dver);       /* EFI_BUFFER_TOO_SMALL */
    msz+=8*dsz;
    if(map) BS->FreePool(map);
    map=NULL;
    if(BS->AllocatePool(EfiLoaderData,msz,(VOID**)&map)||!map) return EFI_LOAD_ERROR;
    if(BS->GetMemoryMap(&msz,map,&key,&dsz,&dver)) continue;

    UINT64 ram=0;
    for(UINTN o=0;o<msz;o+=dsz){
      EFI_MEMORY_DESCRIPTOR *d=(EFI_MEMORY_DESCRIPTOR*)((UINT8*)map+o);
      switch(d->Type){
        case EfiLoaderCode: case EfiLoaderData:
        case EfiBootServicesCode: case EfiBootServicesData:
        case EfiConventionalMemory:
          ram+=d->NumberOfPages<<12; break;
        default: break;
      }
    }
    *total_ram=ram;

    if(!ST->BootServices->ExitBootServices(image,key)) return EFI_SUCCESS;
  }
  return EFI_LOAD_ERROR;
}
#endif /* __x86_64__ */

/* forward decls: text is composed into the in-memory frame below */
static void draw_title(EFI_GRAPHICS_OUTPUT_BLT_PIXEL *frame, UINT32 fw, UINT32 fh);
static void draw_version(EFI_GRAPHICS_OUTPUT_BLT_PIXEL *frame, UINT32 fw, UINT32 fh);

/* splash state kept for the overlay console: g_frame stays allocated as the
 * pristine background the translucent panel re-blends from on every update */
static EFI_GRAPHICS_OUTPUT_PROTOCOL *g_gop;
static EFI_GRAPHICS_OUTPUT_BLT_PIXEL *g_frame;
static UINT32 g_sw, g_sh;
static int g_use_blt;      /* present via firmware Blt (no mappable fb) */
static int g_post_ebs;     /* boot services gone: firmware Blt unusable */

/* Compose the entire splash (background + scaled fish + title + version) in
 * one in-memory BGRA frame, then present it in a single pass. Nothing ever
 * reads the screen back: firmware Blt(VideoToBltBuffer) may return a stale
 * shadow of the text console instead of live VRAM, which used to leave old
 * boot-log text visible behind the title box on real hardware. */
static void draw(EFI_GRAPHICS_OUTPUT_PROTOCOL *gop, UINT8 *asset){
  EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *mi = gop->Mode->Info;
  UINT32 *fb = (UINT32*)(UINTN)gop->Mode->FrameBufferBase;
  UINT32 sw = mi->HorizontalResolution, sh = mi->VerticalResolution;
  UINT32 pitch = mi->PixelsPerScanLine;

  SbmpHeader *h=(SbmpHeader*)asset;
  UINT8 *px = asset+sizeof(SbmpHeader);   /* BGRA rows, top-first */
  UINT32 iw=h->width, ih=h->height;

  /* scale-to-fit (integer nearest neighbour), preserve aspect, centre */
  /* dst dims */
  UINT64 dw, dh;
  if((UINT64)iw*sh <= (UINT64)ih*sw){ dh=sh; dw=(UINT64)iw*sh/ih; }
  else                              { dw=sw; dh=(UINT64)ih*sw/iw; }
  if(dw==0)dw=1; if(dh==0)dh=1;
  UINT32 ox=(sw-(UINT32)dw)/2, oy=(sh-(UINT32)dh)/2;

  /* PixelBitMask does not imply 32bpp: the pixel size is the highest set bit
   * across all masks, rounded up to whole bytes. Direct stores below assume
   * 32bpp, so anything else must go through the firmware Blt path. */
  UINT32 bpp=32;
  if(mi->PixelFormat==PixelBitMask){
    UINT32 m = mi->PixelInformation.RedMask | mi->PixelInformation.GreenMask |
               mi->PixelInformation.BlueMask | mi->PixelInformation.ReservedMask;
    bpp=0; while(m){ bpp++; m>>=1; }
    bpp=(bpp+7)&~7u;
  }
  int use_blt = (mi->PixelFormat==PixelBltOnly ||
                 (mi->PixelFormat==PixelBitMask && bpp!=32));
  g_gop=gop; g_sw=sw; g_sh=sh; g_use_blt=use_blt;

  EFI_GRAPHICS_OUTPUT_BLT_PIXEL *frame=NULL;
  if(BS->AllocatePool(EfiLoaderData,(UINTN)sw*sh*4,(VOID**)&frame) || !frame){
    /* out of pool: paint background + fish straight to the screen, skip text */
    if(use_blt){
      EFI_GRAPHICS_OUTPUT_BLT_PIXEL bgp = {30,12,6,0};   /* deep sea blue */
      gop->Blt(gop,&bgp,EfiBltVideoFill,0,0,0,0,sw,sh,0);
      return;
    }
    UINT32 bg = mkpix(mi, 6, 12, 30);
    for(UINT32 y=0;y<sh;y++){ UINT32 *row=fb+(UINTN)y*pitch; for(UINT32 x=0;x<sw;x++) row[x]=bg; }
    for(UINT32 dy=0; dy<dh; dy++){
      UINT32 sy = (UINT32)((UINT64)dy*ih/dh); if(sy>=ih) sy=ih-1;
      UINT32 *drow = fb + (UINTN)(oy+dy)*pitch + ox;
      UINT8  *srow = px + (UINTN)sy*iw*4;
      for(UINT32 dx=0; dx<dw; dx++){
        UINT32 sx=(UINT32)((UINT64)dx*iw/dw); if(sx>=iw) sx=iw-1;
        UINT8 *p=srow+(UINTN)sx*4;             /* B,G,R,A */
        drow[dx]=mkpix(mi, p[2], p[1], p[0]);
      }
    }
    return;
  }

  /* background: deep sea blue */
  EFI_GRAPHICS_OUTPUT_BLT_PIXEL bgp = {30,12,6,0};
  for(UINTN i=0;i<(UINTN)sw*sh;i++) frame[i]=bgp;

  /* scaled fish, centred; asset pixels are already BGRA = BLT pixel layout */
  for(UINT32 dy=0; dy<dh; dy++){
    UINT32 sy = (UINT32)((UINT64)dy*ih/dh); if(sy>=ih) sy=ih-1;
    EFI_GRAPHICS_OUTPUT_BLT_PIXEL *drow = frame + (UINTN)(oy+dy)*sw + ox;
    UINT8 *srow = px + (UINTN)sy*iw*4;
    for(UINT32 dx=0; dx<dw; dx++){
      UINT32 sx=(UINT32)((UINT64)dx*iw/dw); if(sx>=iw) sx=iw-1;
      drow[dx]=*(EFI_GRAPHICS_OUTPUT_BLT_PIXEL*)(srow+(UINTN)sx*4);
    }
  }

  draw_title(frame, sw, sh);
  draw_version(frame, sw, sh);

  /* present the finished frame in one pass */
  if(use_blt){
    gop->Blt(gop,frame,EfiBltBufferToVideo,0,0,0,0,sw,sh,0);
  }else if(mi->PixelFormat==PixelBlueGreenRedReserved8BitPerColor){
    /* frame already matches the native layout; pitch may exceed width */
    for(UINT32 y=0;y<sh;y++)
      memcpy(fb+(UINTN)y*pitch, frame+(UINTN)y*sw, (UINTN)sw*4);
  }else{
    for(UINT32 y=0;y<sh;y++){
      UINT32 *row=fb+(UINTN)y*pitch;
      EFI_GRAPHICS_OUTPUT_BLT_PIXEL *srow=frame+(UINTN)y*sw;
      for(UINT32 x=0;x<sw;x++)
        row[x]=mkpix(mi, srow[x].Red, srow[x].Green, srow[x].Blue);
    }
  }
  g_frame=frame;    /* kept: the overlay console re-blends from it */
}

/* ---- boot console overlay ----------------------------------------------
 * Big translucent panel, bottom-left over the splash, replaying the boot
 * log with its colors and following new lines live. Composed from g_frame
 * into its own buffer, presented as one rectangle - no VRAM read-back. */
static EFI_GRAPHICS_OUTPUT_BLT_PIXEL *ol_panel;
static UINT32 pl_x, pl_y, pl_w, pl_h, pl_pad, pl_scale, pl_cols, pl_rows;

/* EFI console palette, {B,G,R} tuned for the deep-sea splash */
static const UINT8 OL_RGB[16][3] = {
  { 40, 28, 16},{230,100, 40},{ 90,200, 80},{200,190, 60},
  { 70, 70,230},{200, 80,190},{ 60,130,180},{205,195,185},
  {135,120,105},{255,170,110},{140,235,120},{255,255,  0},
  {110,110,255},{200,140,255},{100,220,250},{255,255,255},
};

static void ol_present(void){
  if(!ol_panel) return;
  if(g_use_blt){
    if(g_post_ebs) return;             /* firmware Blt died with boot services */
    g_gop->Blt(g_gop,ol_panel,EfiBltBufferToVideo,0,0,pl_x,pl_y,pl_w,pl_h,(UINTN)pl_w*4);
    return;
  }
  EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *mi=g_gop->Mode->Info;
  UINT32 *fb=(UINT32*)(UINTN)g_gop->Mode->FrameBufferBase;
  UINT32 pitch=mi->PixelsPerScanLine;
  if(mi->PixelFormat==PixelBlueGreenRedReserved8BitPerColor){
    for(UINT32 y=0;y<pl_h;y++)
      memcpy(fb+(UINTN)(pl_y+y)*pitch+pl_x, ol_panel+(UINTN)y*pl_w, (UINTN)pl_w*4);
  }else{
    for(UINT32 y=0;y<pl_h;y++){
      UINT32 *row=fb+(UINTN)(pl_y+y)*pitch+pl_x;
      EFI_GRAPHICS_OUTPUT_BLT_PIXEL *s=ol_panel+(UINTN)y*pl_w;
      for(UINT32 x=0;x<pl_w;x++) row[x]=mkpix(mi,s[x].Red,s[x].Green,s[x].Blue);
    }
  }
}

static void ol_flush(void){
  if(!ol_panel||!g_frame) return;
  /* translucent dark glass over the pristine splash (~66% tint) */
  for(UINT32 y=0;y<pl_h;y++){
    EFI_GRAPHICS_OUTPUT_BLT_PIXEL *src=g_frame+(UINTN)(pl_y+y)*g_sw+pl_x;
    EFI_GRAPHICS_OUTPUT_BLT_PIXEL *dst=ol_panel+(UINTN)y*pl_w;
    for(UINT32 x=0;x<pl_w;x++){
      dst[x].Blue    =(UINT8)(((UINT32)src[x].Blue *88 + 26*168)>>8);
      dst[x].Green   =(UINT8)(((UINT32)src[x].Green*88 + 14*168)>>8);
      dst[x].Red     =(UINT8)(((UINT32)src[x].Red  *88 +  8*168)>>8);
      dst[x].Reserved=0;
    }
  }
  /* hairline border */
  EFI_GRAPHICS_OUTPUT_BLT_PIXEL bd={150,110,70,0};
  for(UINT32 x=0;x<pl_w;x++){ ol_panel[x]=bd; ol_panel[(UINTN)(pl_h-1)*pl_w+x]=bd; }
  for(UINT32 y=0;y<pl_h;y++){ ol_panel[(UINTN)y*pl_w]=bd; ol_panel[(UINTN)y*pl_w+pl_w-1]=bd; }

  /* tail of the log that fits the panel */
  UINT32 total=ol_row+1;
  UINT32 first= total>pl_rows ? total-pl_rows : 0;
  for(UINT32 r=0; first+r<total && r<pl_rows; r++){
    OlCell *line=ol_log[first+r];
    UINT32 py0=pl_pad+r*16*pl_scale;
    for(UINT32 c=0;c<pl_cols && line[c].ch;c++){
      char ch=line[c].ch;
      if(ch<FONT_FIRST||ch>FONT_LAST) ch=' ';
      const unsigned char *gl=font8x16[ch-FONT_FIRST];
      const UINT8 *rgb=OL_RGB[line[c].attr&15];
      EFI_GRAPHICS_OUTPUT_BLT_PIXEL col={rgb[0],rgb[1],rgb[2],0};
      UINT32 px0=pl_pad+c*8*pl_scale;
      for(UINT32 gy=0;gy<16;gy++){
        unsigned char bits=gl[gy]; if(!bits) continue;
        for(UINT32 gx=0;gx<8;gx++){
          if(!(bits&(0x80>>gx))) continue;
          for(UINT32 sy2=0;sy2<pl_scale;sy2++)for(UINT32 sx2=0;sx2<pl_scale;sx2++)
            ol_panel[(UINTN)(py0+gy*pl_scale+sy2)*pl_w+px0+gx*pl_scale+sx2]=col;
        }
      }
    }
  }
  ol_present();
}

/* geometry + buffer; then flip logging over to the overlay */
static void ol_init(void){
  if(!g_frame) return;                       /* splash fell back: no overlay */
  pl_scale = g_sh/800; if(pl_scale<1) pl_scale=1; if(pl_scale>3) pl_scale=3;
  pl_pad   = 12*pl_scale;
  pl_w = g_sw*60/100; pl_h = g_sh*44/100;
  pl_x = g_sw*2/100;
  pl_y = g_sh - g_sh*3/100 - pl_h;
  pl_cols=(pl_w-2*pl_pad)/(8*pl_scale);
  pl_rows=(pl_h-2*pl_pad)/(16*pl_scale);
  if(pl_cols>OL_COLS) pl_cols=OL_COLS;
  if(BS->AllocatePool(EfiLoaderData,(UINTN)pl_w*pl_h*4,(VOID**)&ol_panel)||!ol_panel)
    { ol_panel=NULL; return; }
  ol_live=1;
  ol_flush();
}

/* A GOP is usable only if it reports a real mode with a nonzero resolution. */
static int gop_ok(EFI_GRAPHICS_OUTPUT_PROTOCOL *g){
  return g && g->Mode && g->Mode->Info &&
         g->Mode->Info->HorizontalResolution && g->Mode->Info->VerticalResolution;
}

/* ---- version badge ------------------------------------------------------ */

/* 8x8 glyphs, bit 7 = leftmost pixel; just the chars a version string needs. */
typedef struct { char c; UINT8 rows[8]; } Glyph;
static const Glyph font[] = {
  {'0',{0x3C,0x66,0x6E,0x76,0x66,0x66,0x3C,0x00}},
  {'1',{0x18,0x38,0x18,0x18,0x18,0x18,0x7E,0x00}},
  {'2',{0x3C,0x66,0x06,0x0C,0x18,0x30,0x7E,0x00}},
  {'3',{0x3C,0x66,0x06,0x1C,0x06,0x66,0x3C,0x00}},
  {'4',{0x0C,0x1C,0x3C,0x6C,0x7E,0x0C,0x0C,0x00}},
  {'5',{0x7E,0x60,0x7C,0x06,0x06,0x66,0x3C,0x00}},
  {'6',{0x3C,0x66,0x60,0x7C,0x66,0x66,0x3C,0x00}},
  {'7',{0x7E,0x06,0x0C,0x18,0x30,0x30,0x30,0x00}},
  {'8',{0x3C,0x66,0x66,0x3C,0x66,0x66,0x3C,0x00}},
  {'9',{0x3C,0x66,0x66,0x3E,0x06,0x66,0x3C,0x00}},
  {'.',{0x00,0x00,0x00,0x00,0x00,0x18,0x18,0x00}},
  {'v',{0x00,0x00,0x66,0x66,0x66,0x3C,0x18,0x00}},
  {'S',{0x3C,0x66,0x60,0x3C,0x06,0x66,0x3C,0x00}},
  {'O',{0x3C,0x66,0x66,0x66,0x66,0x66,0x3C,0x00}},
  {'a',{0x00,0x00,0x3C,0x06,0x3E,0x66,0x3E,0x00}},
  {'b',{0x60,0x60,0x7C,0x66,0x66,0x66,0x7C,0x00}},
  {'c',{0x00,0x00,0x3C,0x66,0x60,0x66,0x3C,0x00}},
  {'m',{0x00,0x00,0x66,0x7F,0x6B,0x6B,0x63,0x00}},
  {'p',{0x00,0x00,0x7C,0x66,0x66,0x7C,0x60,0x60}},
  {'s',{0x00,0x00,0x3E,0x60,0x3C,0x06,0x7C,0x00}},
};

static const UINT8 *glyph(char c){
  for(UINTN i=0;i<sizeof(font)/sizeof(font[0]);i++) if(font[i].c==c) return font[i].rows;
  return NULL;
}

/* Padded text-box geometry, shared by the renderer and its callers:
 * 8px glyphs plus 2*scale padding on every side. */
static UINT32 text_box_w(UINTN len, UINT32 scale){ return ((UINT32)len*8+4)*scale; }
static UINT32 text_box_h(UINT32 scale)           { return 12*scale; }

/* Paint a string at (x0,y0) = top-left of its padded box, straight into the
 * in-memory frame (fw x fh BGRA). Composites over whatever the frame already
 * holds - never reads the screen. Box: w=(8*len+4)*scale, h=12*scale.
 * Chars from index accent_at onward are drawn cyan instead of white; the
 * dark outline/shadow is the same for both. */
static void draw_text(EFI_GRAPHICS_OUTPUT_BLT_PIXEL *frame, UINT32 fw, UINT32 fh,
                      const char *s, UINT32 scale, UINT32 x0, UINT32 y0, UINTN accent_at){
  UINTN len=0; while(s[len]) len++;

  UINT32 pad=2*scale;
  UINT32 w=text_box_w(len,scale), h=text_box_h(scale);
  if(x0+w>fw||y0+h>fh) return;

  /* pass 0 = drop shadow (dark, offset), pass 1 = colored text */
  for(int pass=0;pass<2;pass++){
    UINT32 off = pass ? 0 : (scale>3 ? scale/3 : 1);
    for(UINTN ci=0;ci<len;ci++){
      EFI_GRAPHICS_OUTPUT_BLT_PIXEL col = !pass
        ? (EFI_GRAPHICS_OUTPUT_BLT_PIXEL){10,16,28,0}            /* shadow */
        : ci>=accent_at
          ? (EFI_GRAPHICS_OUTPUT_BLT_PIXEL){255,255,0,0}         /* cyan   */
          : (EFI_GRAPHICS_OUTPUT_BLT_PIXEL){255,255,255,0};      /* white  */
      const UINT8 *g=glyph(s[ci]); if(!g) continue;
      for(UINT32 gy=0;gy<8;gy++){
        UINT8 bits=g[gy]; if(!bits) continue;
        for(UINT32 gx=0;gx<8;gx++){
          if(!(bits&(0x80>>gx))) continue;
          for(UINT32 py=0;py<scale;py++)for(UINT32 px=0;px<scale;px++){
            UINT32 X=pad+(UINT32)ci*8*scale+gx*scale+px+off;
            UINT32 Y=pad+gy*scale+py+off;
            if(X<w&&Y<h) frame[(UINTN)(y0+Y)*fw+x0+X]=col;
          }
        }
      }
    }
  }
}

/* SBOS_VERSION, large, bottom-right corner. */
static void draw_version(EFI_GRAPHICS_OUTPUT_BLT_PIXEL *frame, UINT32 fw, UINT32 fh){
  UINTN len=sizeof(SBOS_VERSION)-1;

  UINT32 scale = fh/120;                       /* ~64px glyphs at 1080p: large */
  if(scale<2) scale=2; if(scale>12) scale=12;
  while(scale>2 && ((UINT32)len*8+8)*scale > fw) scale--;   /* still must fit */

  UINT32 w=text_box_w(len,scale), h=text_box_h(scale), margin=4*scale;
  if(w+margin>fw||h+margin>fh) return;
  draw_text(frame, fw, fh, SBOS_VERSION, scale, fw-w-margin, fh-h-margin, (UINTN)-1);
}

/* SBOS_NAME, larger still, across the top starting left of centre. */
static void draw_title(EFI_GRAPHICS_OUTPUT_BLT_PIXEL *frame, UINT32 fw, UINT32 fh){
  UINTN len=sizeof(SBOS_NAME)-1;

  UINT32 scale = fh/80;                        /* bigger than the version tag */
  if(scale<2) scale=2; if(scale>16) scale=16;
  while(scale>2 && ((UINT32)len*8+8)*scale > fw) scale--;   /* still must fit */

  UINT32 w=text_box_w(len,scale), h=text_box_h(scale), margin=2*scale;
  if(w+margin>fw||h+margin>fh) return;
  /* centre the text block on the left-middle of the screen (x = fw/4) */
  UINT32 x0 = fw/4 > w/2+margin ? fw/4-w/2 : margin;
  draw_text(frame, fw, fh, SBOS_NAME, scale, x0, margin, len-2);   /* "OS" in cyan */
}

EFI_STATUS EFIAPI efi_main(EFI_HANDLE image, EFI_SYSTEM_TABLE *st){
  ST=st; BS=st->BootServices;
  /* Firmware arms a ~5-minute watchdog that resets the machine unless the app
   * exits or ExitBootServices is called. We idle forever, so disarm it. */
  EFI_STATUS wd = BS->SetWatchdogTimer(0, 0, 0, NULL);

  if(ST->ConOut){
    ST->ConOut->Reset(ST->ConOut, 0);
    if(ST->ConOut->ClearScreen) ST->ConOut->ClearScreen(ST->ConOut);
  }

  /* banner */
  puts16(u"\r\n");
  con_attr(ATTR_TITLE);  puts16(u"  SacabambaspOS ");
  con_attr(ATTR_BRIGHT); puts16(SBOS_VERSION_W);
  con_attr(ATTR_TEXT);   puts16(u" - UEFI boot stage\r\n");
  con_attr(ATTR_DIM);    puts16(u"  ==========================================\r\n\r\n");

  if(wd) log_fail(u"Watchdog disarm refused (will still boot)");
  else   log_ok(u"Watchdog disarmed");

  con_attr(ATTR_BRIGHT);
  if(ST->FirmwareVendor){
    log_tag(u"  OK  ",ATTR_OK); puts16(u"Firmware: ");
    puts16(ST->FirmwareVendor); puts16(u" rev ");
    print_u(ST->FirmwareRevision>>16); puts16(u"."); print_u(ST->FirmwareRevision&0xFFFF);
    puts16(u"\r\n");
  }

  /* On multi-GOP systems (dual GPU, BMC video) LocateProtocol may return a
   * GOP not wired to the visible panel, or one with a 0x0 mode. Prefer the
   * console handle's GOP, then scan all handles, and validate whatever we
   * pick before touching its framebuffer. */
  EFI_GUID gop_guid = EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID;
  EFI_GRAPHICS_OUTPUT_PROTOCOL *gop=NULL, *cand=NULL;
  if(ST->ConsoleOutHandle &&
     !BS->HandleProtocol(ST->ConsoleOutHandle, &gop_guid, (VOID**)&cand) && gop_ok(cand))
    gop=cand;
  if(!gop){
    EFI_HANDLE hs[32]; UINTN bsz=sizeof(hs);
    if(!BS->LocateHandle(2 /*ByProtocol*/, &gop_guid, NULL, &bsz, hs))
      for(UINTN i=0;i<bsz/sizeof(EFI_HANDLE) && !gop;i++){
        cand=NULL;
        if(!BS->HandleProtocol(hs[i], &gop_guid, (VOID**)&cand) && gop_ok(cand)) gop=cand;
      }
  }
  if(!gop){
    cand=NULL;
    if(!BS->LocateProtocol(&gop_guid, NULL, (VOID**)&cand) && gop_ok(cand)) gop=cand;
  }
  if(!gop){
    log_fail(u"No usable Graphics Output Protocol - cannot draw");
    for(;;) __asm__ __volatile__("hlt");
  }
  {
    EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *mi=gop->Mode->Info;
    log_tag(u"  OK  ",ATTR_OK); puts16(u"Display ");
    print_u(mi->HorizontalResolution); puts16(u"x"); print_u(mi->VerticalResolution);
    switch(mi->PixelFormat){
      case PixelBlueGreenRedReserved8BitPerColor: puts16(u" BGRX32"); break;
      case PixelRedGreenBlueReserved8BitPerColor: puts16(u" RGBX32"); break;
      case PixelBitMask:                          puts16(u" bitmask"); break;
      case PixelBltOnly:                          puts16(u" blt-only"); break;
      default: break;
    }
    puts16(u" (GOP)\r\n");
  }

  UINT8 *asset=NULL; UINTN sz=0;
  EFI_STATUS s=load_asset(image,&asset,&sz);
  if(s){
    log_tag(u" FAIL ",ATTR_FAIL); puts16(u"SACABASP.RAW load failed, status ");
    print_hex(s); puts16(u"\r\n\r\n");
    con_attr(ATTR_WARN);
    puts16(u"  Boot halted so you can read the log. Machine untouched.\r\n");
    for(;;) __asm__ __volatile__("hlt");
  }
  {
    SbmpHeader *h=(SbmpHeader*)asset;
    log_tag(u"  OK  ",ATTR_OK); puts16(u"SACABASP.RAW loaded: ");
    print_u(h->width); puts16(u"x"); print_u(h->height); puts16(u" BGRA, ");
    print_u(sz); puts16(u" bytes\r\n");
  }
  log_ok(u"Nothing written to any disk (live mode)");

  con_attr(ATTR_WARN);
  puts16(u"\r\n  Booting splash");
  con_attr(ATTR_DIM);
  for(int i=0;i<3;i++){ BS->Stall(650*1000); puts16(u" ."); }
  BS->Stall(650*1000);
  puts16(u"\r\n");

  draw(gop, asset);
  /* From here on all logging goes to the translucent boot console on the
   * splash; ConOut is never touched again (the firmware text console would
   * paint over the framebuffer). */
  ol_init();

#if defined(__x86_64__)
  /* The kernel renders its own console, so it needs a CPU-mappable 32bpp
   * framebuffer in a layout it understands. */
  EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *mi=gop->Mode->Info;
  UINT32 kfmt=(UINT32)-1;
  if(mi->PixelFormat==PixelBlueGreenRedReserved8BitPerColor) kfmt=SBOS_PIXFMT_BGRX;
  else if(mi->PixelFormat==PixelRedGreenBlueReserved8BitPerColor) kfmt=SBOS_PIXFMT_RGBX;
  else if(mi->PixelFormat==PixelBitMask){
    EFI_PIXEL_BITMASK *m=&mi->PixelInformation;
    if(m->RedMask==0xFF0000&&m->GreenMask==0xFF00&&m->BlueMask==0xFF) kfmt=SBOS_PIXFMT_BGRX;
    if(m->BlueMask==0xFF0000&&m->GreenMask==0xFF00&&m->RedMask==0xFF) kfmt=SBOS_PIXFMT_RGBX;
  }
  if(g_use_blt || kfmt==(UINT32)-1){
    log_fail(u"Framebuffer not kernel-usable - staying on the splash");
    for(;;) __asm__ __volatile__("hlt");
  }

  UINT64 kentry=0, kbase=0;
  s=kernel_load(image,&kentry,&kbase);
  if(s){
    log_tag(u" FAIL ",ATTR_FAIL); puts16(u"KERNEL.ELF load failed, status ");
    print_hex(s); puts16(u"\r\n");
    con_attr(ATTR_WARN); puts16(u"  Staying on the splash. Machine untouched.\r\n");
    for(;;) __asm__ __volatile__("hlt");
  }
  log_tag(u"  OK  ",ATTR_OK); puts16(u"KERNEL.ELF relocated to ");
  print_hex(kbase); puts16(u"\r\n");

  /* kernel heap: EfiLoaderData pages stay ours after ExitBootServices */
  UINT64 heap=0; UINTN heap_pages=32*256;                 /* 32 MiB, halve on failure */
  EFI_STATUS hs=EFI_LOAD_ERROR;
  for(; heap_pages>=2*256; heap_pages/=2)
    if(!(hs=BS->AllocatePages(AllocateAnyPages,EfiLoaderData,heap_pages,&heap))) break;
  if(hs){
    log_fail(u"No room for the kernel heap - staying on the splash");
    for(;;) __asm__ __volatile__("hlt");
  }
  log_tag(u"  OK  ",ATTR_OK); puts16(u"Kernel heap ");
  print_u((UINT64)(heap_pages<<12)>>20); puts16(u" MiB @ "); print_hex(heap);
  puts16(u"\r\n");

  {  /* INIT.RC boot script is optional */
    CHAR16 *rc[]={u"\\SBOS\\INIT.RC", u"\\INIT.RC", u"INIT.RC"};
    UINT8 *rcb=NULL; UINTN rcsz=0;
    if(!load_file(image,rc,3,64*1024,&rcb,&rcsz)){
      bootinfo.initrc_base=(UINT64)(UINTN)rcb; bootinfo.initrc_size=rcsz;
      log_ok(u"INIT.RC loaded");
    }else{
      log_tag(u" INFO ",ATTR_DIM); puts16(u"no INIT.RC (optional)\r\n");
    }
  }

  bootinfo.magic     = SBOS_BOOTINFO_MAGIC;
  bootinfo.fb_base   = gop->Mode->FrameBufferBase;
  bootinfo.fb_width  = mi->HorizontalResolution;
  bootinfo.fb_height = mi->VerticalResolution;
  bootinfo.fb_pitch  = mi->PixelsPerScanLine;
  bootinfo.fb_format = kfmt;
  bootinfo.heap_base = heap;
  bootinfo.heap_size = (UINT64)heap_pages<<12;
  bootinfo.rsdp      = find_rsdp();

  con_attr(ATTR_WARN);
  puts16(u"\r\n  Handing over to the kernel...\r\n");
  BS->Stall(900*1000);

  UINT64 total_ram=0;
  s=exit_boot_services(image,&total_ram);
  if(s){
    log_fail(u"ExitBootServices refused - staying on the splash");
    for(;;) __asm__ __volatile__("hlt");
  }
  g_post_ebs=1;
  bootinfo.total_ram=total_ram;

  /* kernel entry is SysV ABI; this call never returns */
  ((void (*)(SbosBootInfo*))(UINTN)kentry)(&bootinfo);
  for(;;) __asm__ __volatile__("hlt");
#else
  /* ia32: the stage-1 kernel is x86-64 only; keep the splash (live mode) */
  log_tag(u" INFO ",ATTR_DIM); puts16(u"32-bit EFI: kernel stage skipped, splash only\r\n");
  for(;;) __asm__ __volatile__("hlt");
#endif
  return EFI_SUCCESS;
}
