#!/usr/bin/env python3
"""mkfont.py - convert a PSF1/PSF2 console font into a C header.

Extracts the 8x16 glyphs for printable ASCII (0x20..0x7E) and emits an
array indexed by (ch - 0x20). Used by both the UEFI boot stage's overlay
console and the kernel's framebuffer console.

Usage: mkfont.py OUT.h [FONT.psf[.gz]] ...
Tries each font path in order; the default list covers Debian/Ubuntu.
"""
import gzip, struct, sys

PSF1_MAGIC = b"\x36\x04"
PSF2_MAGIC = b"\x72\xb5\x4a\x86"

def read_font(path):
    data = open(path, "rb").read()
    if data[:2] == b"\x1f\x8b":
        data = gzip.decompress(data)
    if data[:2] == PSF1_MAGIC:
        mode, charsize = data[2], data[3]
        nglyph = 512 if (mode & 1) else 256
        width, height, stride = 8, charsize, 1
        hdr = 4
        has_table = bool(mode & 0x02 or mode & 0x04)
        glyphs = [data[hdr+i*charsize : hdr+(i+1)*charsize] for i in range(nglyph)]
        table_off = hdr + nglyph*charsize
        unimap = parse_psf1_table(data, table_off, nglyph) if has_table else None
        return glyphs, width, height, stride, unimap
    if data[:4] == PSF2_MAGIC:
        (ver, hdr, flags, nglyph, charsize, height, width) = struct.unpack("<7I", data[4:32])
        stride = (width + 7) // 8
        glyphs = [data[hdr+i*charsize : hdr+(i+1)*charsize] for i in range(nglyph)]
        unimap = parse_psf2_table(data, hdr + nglyph*charsize, nglyph) if (flags & 1) else None
        return glyphs, width, height, stride, unimap
    raise ValueError(f"{path}: not a PSF font")

def parse_psf1_table(data, off, nglyph):
    unimap, i = {}, off
    for g in range(nglyph):
        while i + 1 < len(data):
            (u,) = struct.unpack_from("<H", data, i); i += 2
            if u == 0xFFFF: break
            if u == 0xFFFE: continue          # sequence start: skip combiners
            unimap.setdefault(u, g)
    return unimap

def parse_psf2_table(data, off, nglyph):
    unimap, i = {}, off
    for g in range(nglyph):
        start = i
        while i < len(data) and data[i] != 0xFF: i += 1
        for ch in data[start:i].decode("utf-8", "ignore"):
            unimap.setdefault(ord(ch), g)
        i += 1
    return unimap

def main():
    out = sys.argv[1]
    candidates = sys.argv[2:] or [
        "/usr/share/consolefonts/Lat15-VGA16.psf.gz",
        "/usr/share/consolefonts/Lat15-Fixed16.psf.gz",
        "/usr/share/consolefonts/Uni2-VGA16.psf.gz",
        "/usr/share/kbd/consolefonts/lat1-16.psfu.gz",
    ]
    font = None
    for p in candidates:
        try:
            font = read_font(p); src = p; break
        except (OSError, ValueError):
            continue
    if not font:
        sys.exit("mkfont: no usable PSF console font found (install 'kbd' or 'console-setup')")
    glyphs, width, height, stride, unimap = font
    if width != 8 or height != 16 or stride != 1:
        sys.exit(f"mkfont: {src} is {width}x{height}, need 8x16")

    rows = []
    for ch in range(0x20, 0x7F):
        g = unimap.get(ch, ch if unimap is None and ch < len(glyphs) else None)
        bits = glyphs[g] if g is not None and g < len(glyphs) else bytes(16)
        rows.append((ch, bits))

    with open(out, "w") as f:
        f.write("/* generated by tools/mkfont.py from %s - do not edit */\n" % src)
        f.write("/* 8x16 glyphs for ASCII 0x20..0x7E, bit 7 = leftmost pixel */\n")
        f.write("#define FONT_W 8\n#define FONT_H 16\n#define FONT_FIRST 0x20\n#define FONT_LAST 0x7E\n")
        f.write("static const unsigned char font8x16[95][16] = {\n")
        for ch, bits in rows:
            hexes = ",".join("0x%02X" % b for b in bits)
            name = chr(ch) if ch != 0x2A and ch != 0x2F else chr(ch)  # keep comment safe
            f.write("  {%s}, /* %s */\n" % (hexes, ("'%c'" % ch).replace("*/", "* /")))
        f.write("};\n")
    print(f"mkfont: {out} from {src}")

if __name__ == "__main__":
    main()
